#!/bin/bash

gen_ip () {
  local ip="100.67.224.35"
  local n1=$((1 + $RANDOM % 127))
  local n2=$((1 + $RANDOM % 255))
  local n3=$((1 + $RANDOM % 255))
  local n4=$((1 + $RANDOM % 255))
  n=$((1 + $RANDOM % 8))
  case $n in
    1)
      ip="${n1}.${n2}.${n3}.${n4}"
    ;;
    2) ip="101.67.224.35";;
    3) ip="41.27.144.140";;
    4) ip="27.17.225.75";;
    5) ip="111.87.21.39";;
    6) ip="42.69.214.15";;
    7) ip="104.201.24.55";;
    8) ip="85.73.227.39";;
  esac
  echo $ip
}